version: '3.1'
services:
    deb:
        image: mariadb
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
        - "3306:3306"
        volumes:
        - devdb_data:/var/lib/mysql

volumes:
    devdb_data: